### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PhilJbt** [janhsimon/DanishVerbs#1]
Could you please tell under which license this repository is?
Especially the file [verbs.js](https://github.com/janhsimon/DanishVerbs/blob/master/verbs.js).

**Comment by janhsimon** [comment]
Hi, I've added the unlicense license to the project. That means it's completely in the public domain, do with it whatever you want. ;) Enjoy!

**Comment by PhilJbt** [comment]
That's perfect, thank you very much!
